const list = [
    {
        id:1,
        title:"my first books",
        auther:"by wonder full books",
        price:89,
        img:"https://benthambooks.com/slider-books/9789815124453.png",
        amount: 1,
    },
    {
        id:2,
        title:"my first books",
        auther:"by wonder full books",
        price:209,
        img:"https://benthambooks.com/slider-books/9789815124453.png",
        amount: 1,
    },
    {
        id:3,
        title:"my first books",
        auther:"by wonder full books",
        price:199,
        img:"https://benthambooks.com/slider-books/9789815124453.png",
        amount: 1,
    },
    {
        id:4,
        title:"my first books",
        auther:"by wonder full books",
        price:200,
        img:"https://benthambooks.com/slider-books/9789815124453.png",
        amount: 1,
    },
    {
        id:5,
        title:"my first books",
        auther:"by wonder full books",
        price:499,
        img:"https://benthambooks.com/slider-books/9789815124453.png",
        amount: 1,
    },
    {
        id:6,
        title:"my first books",
        auther:"by wonder full books",
        price:60,
        img:"https://benthambooks.com/slider-books/9789815124453.png",
        amount: 1,
    },
    {
        id:7,
        title:"my first books",
        auther:"by wonder full books",
        price:99,
        img:"https://benthambooks.com/slider-books/9789815124453.png",
        amount: 1,
    },
    {
        id:8,
        title:"my first books",
        auther:"by wonder full books",
        price:150,
        img:"https://benthambooks.com/slider-books/9789815124453.png",
        amount: 1,
    },
];
export default list